<?php
// i18n-map.php @generated by automattic/jetpack-composer-plugin
return array(
  'domain' => 'jetpack-mu-wpcom-plugin',
  'type' => 'plugins',
  'packages' => array(
    'jetpack-admin-ui' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-admin-ui',
      'ver' => '0.5.9',
    ),
    'jetpack-assets' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-assets',
      'ver' => '4.0.20',
    ),
    'jetpack-blaze' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-blaze',
      'ver' => '0.25.25-alpha1747324418',
    ),
    'jetpack-calypsoify' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-calypsoify',
      'ver' => '0.2.4-alpha1747324418',
    ),
    'jetpack-classic-theme-helper' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-classic-theme-helper',
      'ver' => '0.13.1-alpha1747324418',
    ),
    'jetpack-compat' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-compat',
      'ver' => '4.0.1',
    ),
    'jetpack-connection' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-connection',
      'ver' => '6.11.4',
    ),
    'jetpack-google-analytics' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-google-analytics',
      'ver' => '0.3.2-alpha1745512883',
    ),
    'jetpack-ip' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-ip',
      'ver' => '0.4.9',
    ),
    'jetpack-jitm' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-jitm',
      'ver' => '4.2.17',
    ),
    'jetpack-masterbar' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-masterbar',
      'ver' => '0.17.3-alpha1747324418',
    ),
    'jetpack-mu-wpcom' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-mu-wpcom',
      'ver' => '6.4.0-alpha1747395336',
    ),
    'jetpack-password-checker' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-password-checker',
      'ver' => '0.4.8',
    ),
    'jetpack-scheduled-updates' => array(
      'path' => 'jetpack_vendor/automattic/scheduled-updates',
      'ver' => '0.14.2-alpha1745512883',
    ),
    'jetpack-stats' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-stats',
      'ver' => '0.16.2',
    ),
    'jetpack-stats-admin' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-stats-admin',
      'ver' => '0.26.2',
    ),
    'jetpack-subscribers-dashboard' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-subscribers-dashboard',
      'ver' => '0.1.11-alpha1747324418',
    ),
    'jetpack-sync' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-sync',
      'ver' => '4.13.0',
    ),
  ),
);
