<?php
// i18n-map.php @generated by automattic/jetpack-composer-plugin
return array(
  'domain' => 'jetpack-mu-wpcom-plugin',
  'type' => 'plugins',
  'packages' => array(
    'jetpack-admin-ui' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-admin-ui',
      'ver' => '0.5.11',
    ),
    'jetpack-assets' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-assets',
      'ver' => '4.3.25',
    ),
    'jetpack-blaze' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-blaze',
      'ver' => '0.27.4',
    ),
    'jetpack-block-delimiter' => array(
      'path' => 'jetpack_vendor/automattic/block-delimiter',
      'ver' => '0.3.5',
    ),
    'jetpack-classic-theme-helper' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-classic-theme-helper',
      'ver' => '0.14.16-alpha1771881388',
    ),
    'jetpack-compat' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-compat',
      'ver' => '4.0.1',
    ),
    'jetpack-connection' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-connection',
      'ver' => '8.0.0',
    ),
    'jetpack-explat' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-explat',
      'ver' => '0.4.13',
    ),
    'jetpack-google-analytics' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-google-analytics',
      'ver' => '0.3.4',
    ),
    'jetpack-ip' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-ip',
      'ver' => '0.4.10',
    ),
    'jetpack-jitm' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-jitm',
      'ver' => '4.3.23',
    ),
    'jetpack-masterbar' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-masterbar',
      'ver' => '0.27.14-alpha1771881388',
    ),
    'jetpack-mu-wpcom' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-mu-wpcom',
      'ver' => '6.10.0-alpha1771904643',
    ),
    'jetpack-newsletter' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-newsletter',
      'ver' => '0.5.0',
    ),
    'jetpack-password-checker' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-password-checker',
      'ver' => '0.4.9',
    ),
    'jetpack-scheduled-updates' => array(
      'path' => 'jetpack_vendor/automattic/scheduled-updates',
      'ver' => '0.14.6-alpha1770098352',
    ),
    'jetpack-stats' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-stats',
      'ver' => '0.18.0',
    ),
    'jetpack-stats-admin' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-stats-admin',
      'ver' => '0.30.7',
    ),
    'jetpack-subscribers-dashboard' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-subscribers-dashboard',
      'ver' => '0.4.19',
    ),
    'jetpack-sync' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-sync',
      'ver' => '4.29.1-alpha1771924014',
    ),
  ),
);
